/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pratik' at '12/24/16 2:51 PM' with Gradle 3.2.1
 *
 * @author pratik, @date 12/24/16 2:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
